import {useEffect, useState} from 'react';

import fetchData from '../utils/fetchData';

const useMedia = () => {
  const [mediaArray, setMediaArray] = useState([]);

  useEffect(() => {
    const getMedia = async () => {
      try {
        const mediaData = await fetchData(
          import.meta.env.VITE_MEDIA_API + '/media'
        );

        const userListPromises = mediaData.map((media) =>
          fetchData(import.meta.env.VITE_AUTH_API + '/users/' + media.user_id)
        );

        const userListData = await Promise.all(userListPromises);

        const combinedData = mediaData.map((item) => {
          const foundUser = userListData.find(
            (user) => user.user_id === item.user_id
          );

          return {
            ...item,
            user: foundUser,
          };
        });

        combinedData.reverse();

        setMediaArray(combinedData);
      } catch (error) {
        console.log(error);
      }
    };

    getMedia();
  }, []);

  const postMedia = async (file, inputs, token) => {
    // TODO: create a suitable object for Media API: without media_id, user_id, thumbnail and created_at. All those are generated by the API. See the media API documentation.
    // TODO: post the data to Media API and get the data as MediaResponse
    // TODO: return the data

    const data = {
      ...file,
      ...inputs,
    };

    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(data),
    };
    console.log(fetchOptions);
    const loginResult = await fetchData(
      import.meta.env.VITE_MEDIA_API + '/media',
      fetchOptions
    );
    return loginResult;
  };

  const deleteMedia = async (media_id, token) => {
    const fetchOptions = {
      method: 'DELETE',
      headers: {
        Authorization: `Bearer ${token}`,
      },
    };

    return await fetchData(
      `${import.meta.env.VITE_MEDIA_API}/media/${media_id}`,
      fetchOptions
    );
  };

  return {mediaArray, postMedia, deleteMedia};
};

const useLike = (media_id) => {
  const [likeCount, setLikeCount] = useState(0);

  useEffect(() => {
    const getCounts = async () => {
      const likeCount = await getLikeCountByMediaId(media_id);
      if (likeCount?.count) {
        setLikeCount(likeCount.count);
      }
    };

    getCounts();
  }, []);

  const postLike = async () => {
    const token = localStorage.getItem('token');
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({media_id}),
    };

    const result = await fetchData(
      import.meta.env.VITE_MEDIA_API + '/likes',
      fetchOptions
    );

    setLikeCount(likeCount + 1);

    return result;
  };

  const getLikeCountByMediaId = async () =>
    await fetchData(
      import.meta.env.VITE_MEDIA_API + '/likes/count/' + media_id
    );

  return {likeCount, postLike, getLikeCountByMediaId};
};

const useFile = () => {
  const uploadFile = async (file, token) => {
    const formData = new FormData();
    formData.append('file', file);

    const fetchOptions = {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: formData,
    };

    const result = await fetchData(
      import.meta.env.VITE_UPLOAD_SERVER + '/upload',
      fetchOptions
    );
    return result;
  };

  return {uploadFile};
};

const useAuthentication = () => {
  const postLogin = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    console.log(fetchOptions);
    const loginResult = await fetchData(
      import.meta.env.VITE_AUTH_API + '/auth/login',
      fetchOptions
    );
    return loginResult;
  };

  const createUser = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };

    const result = await fetchData(
      import.meta.env.VITE_AUTH_API + '/users',
      fetchOptions
    );
    return result;
  };

  const checkToken = async (token) => {
    const fetchOptions = {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
    };

    const result = await fetchData(
      import.meta.env.VITE_AUTH_API + '/users/token',
      fetchOptions
    );
    return result;
  };

  return {postLogin, createUser, checkToken};
};

const useUser = () => {
  const getUserByToken = async () => {};

  return {getUserByToken};
};

export {useMedia, useAuthentication, useUser, useFile, useLike};
